import type { UnitHold, WaitlistEntry, HoldHistoryEvent, HoldNotification, HoldAnalytics } from '../types';

export const mockHolds: UnitHold[] = [
  {
    id: 'H-001',
    unitId: 'U-101',
    unitNumber: 'A-1402',
    projectId: 'P-1',
    projectName: 'Skyline Residences',
    builderId: 'B-01',
    builderName: 'Prestige Group',
    clientId: 'C-1002',
    clientName: 'Priya Sharma',
    clientPhone: '+91 98765 43210',
    userId: 'U-AGENT-01',
    brokerName: 'Mike Ross',
    holdDuration: 48,
    createdDate: '2026-06-12T09:00:00Z',
    expiryDate: '2026-06-14T09:00:00Z',
    status: 'Active',
    priority: 'VIP',
    remarks: 'Client is highly interested. Confirmed verbal intent. Token cheque to be submitted by EOD.',
    tokenPaid: true,
    tokenAmount: '₹50,000',
    extensionsUsed: 0,
    maxExtensions: 2,
    unitPrice: '₹4.2 Cr',
    unitConfig: '3 BHK',
    floorNumber: 14,
    towerName: 'Tower A',
  },
  {
    id: 'H-002',
    unitId: 'U-205',
    unitNumber: 'B-2101',
    projectId: 'P-2',
    projectName: 'Zenith Towers',
    builderId: 'B-02',
    builderName: 'DLF Limited',
    clientId: 'C-1004',
    clientName: 'Sneha Desai',
    clientPhone: '+91 87654 32109',
    userId: 'U-AGENT-02',
    brokerName: 'Harvey Specter',
    holdDuration: 24,
    createdDate: '2026-06-11T10:00:00Z',
    expiryDate: '2026-06-13T10:00:00Z',
    status: 'Expiring',
    priority: 'High',
    remarks: 'Client needs home loan approval. Bank visit scheduled tomorrow.',
    tokenPaid: false,
    tokenAmount: '₹0',
    extensionsUsed: 1,
    maxExtensions: 2,
    unitPrice: '₹4.3 Cr',
    unitConfig: '4 BHK',
    floorNumber: 21,
    towerName: 'Tower B',
  },
  {
    id: 'H-003',
    unitId: 'U-308',
    unitNumber: 'C-805',
    projectId: 'P-3',
    projectName: 'Oasis Greens',
    builderId: 'B-03',
    builderName: 'Sobha Developers',
    clientId: 'C-1001',
    clientName: 'Rajesh Kumar',
    clientPhone: '+91 76543 21098',
    userId: 'U-AGENT-01',
    brokerName: 'Sarah Jenkins',
    holdDuration: 24,
    createdDate: '2026-06-10T10:00:00Z',
    expiryDate: '2026-06-11T10:00:00Z',
    status: 'Released',
    priority: 'Standard',
    remarks: 'Client decided to look at other options.',
    tokenPaid: false,
    tokenAmount: '₹0',
    extensionsUsed: 0,
    maxExtensions: 2,
    unitPrice: '₹2.8 Cr',
    unitConfig: '2 BHK',
    floorNumber: 8,
    towerName: 'Tower C',
  },
  {
    id: 'H-004',
    unitId: 'U-410',
    unitNumber: 'D-1205',
    projectId: 'P-1',
    projectName: 'Skyline Residences',
    builderId: 'B-01',
    builderName: 'Prestige Group',
    clientId: 'C-1005',
    clientName: 'Arjun Mehta',
    clientPhone: '+91 65432 10987',
    userId: 'U-AGENT-03',
    brokerName: 'Louis Litt',
    holdDuration: 72,
    createdDate: '2026-06-09T14:00:00Z',
    expiryDate: '2026-06-12T14:00:00Z',
    status: 'Converted',
    priority: 'VIP',
    remarks: 'Client confirmed. Booking done.',
    tokenPaid: true,
    tokenAmount: '₹1,00,000',
    extensionsUsed: 1,
    maxExtensions: 2,
    unitPrice: '₹5.1 Cr',
    unitConfig: '4 BHK Penthouse',
    floorNumber: 12,
    towerName: 'Tower D',
  },
  {
    id: 'H-005',
    unitId: 'U-502',
    unitNumber: 'A-0901',
    projectId: 'P-2',
    projectName: 'Zenith Towers',
    builderId: 'B-02',
    builderName: 'DLF Limited',
    clientId: 'C-1008',
    clientName: 'Kavya Reddy',
    clientPhone: '+91 54321 09876',
    userId: 'U-AGENT-02',
    brokerName: 'Harvey Specter',
    holdDuration: 48,
    createdDate: '2026-06-13T08:00:00Z',
    expiryDate: '2026-06-15T08:00:00Z',
    status: 'Active',
    priority: 'High',
    remarks: 'NRI client. Documentation in progress.',
    tokenPaid: false,
    tokenAmount: '₹0',
    extensionsUsed: 0,
    maxExtensions: 2,
    unitPrice: '₹3.7 Cr',
    unitConfig: '3 BHK',
    floorNumber: 9,
    towerName: 'Tower A',
  },
  {
    id: 'H-006',
    unitId: 'U-601',
    unitNumber: 'E-0302',
    projectId: 'P-3',
    projectName: 'Oasis Greens',
    builderId: 'B-03',
    builderName: 'Sobha Developers',
    clientId: 'C-1010',
    clientName: 'Rohan Nair',
    clientPhone: '+91 43210 98765',
    userId: 'U-AGENT-01',
    brokerName: 'Mike Ross',
    holdDuration: 24,
    createdDate: '2026-06-13T06:00:00Z',
    expiryDate: '2026-06-14T06:00:00Z',
    status: 'Extended',
    priority: 'Standard',
    remarks: 'First extension approved by manager.',
    tokenPaid: true,
    tokenAmount: '₹25,000',
    extensionsUsed: 1,
    maxExtensions: 2,
    unitPrice: '₹2.2 Cr',
    unitConfig: '2 BHK',
    floorNumber: 3,
    towerName: 'Tower E',
  },
];

export const mockWaitlist: WaitlistEntry[] = [
  {
    id: 'W-001',
    holdId: 'H-001',
    unitId: 'U-101',
    unitNumber: 'A-1402',
    projectId: 'P-1',
    projectName: 'Skyline Residences',
    clientId: 'C-1006',
    clientName: 'Vikram Malhotra',
    brokerName: 'Louis Litt',
    priority: 'High',
    queuePosition: 1,
    addedAt: '2026-06-12T09:30:00Z',
    notes: 'Client is ready to book immediately if hold is released.'
  },
  {
    id: 'W-002',
    holdId: 'H-002',
    unitId: 'U-205',
    unitNumber: 'B-2101',
    projectId: 'P-2',
    projectName: 'Zenith Towers',
    clientId: 'C-1007',
    clientName: 'Ananya Singh',
    brokerName: 'Rachel Zane',
    priority: 'Standard',
    queuePosition: 1,
    addedAt: '2026-06-11T11:00:00Z',
    notes: 'Waiting for existing hold to expire.'
  },
  {
    id: 'W-003',
    holdId: 'H-001',
    unitId: 'U-101',
    unitNumber: 'A-1402',
    projectId: 'P-1',
    projectName: 'Skyline Residences',
    clientId: 'C-1009',
    clientName: 'Deepak Kapoor',
    brokerName: 'Mike Ross',
    priority: 'VIP',
    queuePosition: 2,
    addedAt: '2026-06-12T10:15:00Z',
    notes: 'VIP client. Prefers this unit specifically.'
  },
];

export const mockHoldHistory: Record<string, HoldHistoryEvent[]> = {
  'H-001': [
    {
      id: 'HH-3', holdId: 'H-001', action: 'Token Received ₹50,000', actionType: 'token',
      performedBy: 'Accounts Dept', performedById: 'ACC-01', timestamp: '2026-06-12T09:15:00Z',
      metadata: { amount: '₹50,000', mode: 'Cheque' }
    },
    {
      id: 'HH-4', holdId: 'H-001', action: 'Hold Created (48h)', actionType: 'created',
      performedBy: 'Mike Ross', performedById: 'U-AGENT-01', timestamp: '2026-06-12T09:00:00Z',
      metadata: { duration: '48 hours', priority: 'VIP' }
    },
  ],
  'H-002': [
    {
      id: 'HH-1', holdId: 'H-002', action: 'Hold Extended 24h (Manager Approval)', actionType: 'extended',
      performedBy: 'System (Mgr: Donna Paulsen)', performedById: 'MGR-01', timestamp: '2026-06-12T10:00:00Z',
      metadata: { extensionHours: '24', approvedBy: 'Donna Paulsen' }
    },
    {
      id: 'HH-2', holdId: 'H-002', action: 'Hold Created (24h)', actionType: 'created',
      performedBy: 'Harvey Specter', performedById: 'U-AGENT-02', timestamp: '2026-06-11T10:00:00Z',
      metadata: { duration: '24 hours', priority: 'High' }
    },
  ],
  'H-004': [
    {
      id: 'HH-5', holdId: 'H-004', action: 'Booking Converted Successfully', actionType: 'converted',
      performedBy: 'Louis Litt', performedById: 'U-AGENT-03', timestamp: '2026-06-12T11:00:00Z',
      metadata: { bookingId: 'BK-9981' }
    },
    {
      id: 'HH-6', holdId: 'H-004', action: 'Hold Extended 24h', actionType: 'extended',
      performedBy: 'System', performedById: 'SYS', timestamp: '2026-06-10T14:00:00Z',
      metadata: { extensionHours: '24' }
    },
    {
      id: 'HH-7', holdId: 'H-004', action: 'Hold Created (72h)', actionType: 'created',
      performedBy: 'Louis Litt', performedById: 'U-AGENT-03', timestamp: '2026-06-09T14:00:00Z',
      metadata: { duration: '72 hours', priority: 'VIP' }
    },
  ],
};

export const mockHoldNotifications: HoldNotification[] = [
  {
    id: 'N-001', holdId: 'H-002', type: 'expiring',
    title: 'Hold Expiring in 2 Hours!',
    message: 'B-2101 at Zenith Towers for Sneha Desai expires at 10:00 AM.',
    timestamp: '2026-06-13T08:00:00Z', read: false, urgency: 'high',
    unitNumber: 'B-2101', projectName: 'Zenith Towers',
  },
  {
    id: 'N-002', holdId: 'H-005', type: 'new',
    title: 'New Hold Created',
    message: 'A-0901 at Zenith Towers held for Kavya Reddy for 48 hours.',
    timestamp: '2026-06-13T08:01:00Z', read: false, urgency: 'low',
    unitNumber: 'A-0901', projectName: 'Zenith Towers',
  },
  {
    id: 'N-003', holdId: 'H-001', type: 'waitlist',
    title: 'New Waitlist Entry',
    message: 'Deepak Kapoor joined waitlist (position 2) for A-1402 via Mike Ross.',
    timestamp: '2026-06-12T10:15:00Z', read: true, urgency: 'medium',
    unitNumber: 'A-1402', projectName: 'Skyline Residences',
  },
  {
    id: 'N-004', holdId: 'H-004', type: 'converted',
    title: 'Hold Converted to Booking! 🎉',
    message: 'D-1205 at Skyline Residences booked by Arjun Mehta. Booking ID: BK-9981.',
    timestamp: '2026-06-12T11:00:00Z', read: true, urgency: 'low',
    unitNumber: 'D-1205', projectName: 'Skyline Residences',
  },
  {
    id: 'N-005', holdId: 'H-006', type: 'extended',
    title: 'Hold Extended',
    message: 'E-0302 at Oasis Greens extended by 24h for Rohan Nair.',
    timestamp: '2026-06-12T06:30:00Z', read: true, urgency: 'medium',
    unitNumber: 'E-0302', projectName: 'Oasis Greens',
  },
];

export const mockHoldAnalytics: HoldAnalytics = {
  totalHolds: 47,
  activeHolds: 8,
  expiringHolds: 3,
  convertedHolds: 21,
  releasedHolds: 15,
  avgHoldDuration: 36.5,
  conversionRate: 44.7,
  extensionRate: 28.3,
  waitlistCount: 7,
  topProject: 'Skyline Residences',
  revenueAtRisk: '₹18.3 Cr',
  thisWeekHolds: 12,
  lastWeekHolds: 9,
};

export const mockClients = [
  { id: 'C-1001', name: 'Rajesh Kumar', phone: '+91 76543 21098', email: 'rajesh@email.com', city: 'Mumbai' },
  { id: 'C-1002', name: 'Priya Sharma', phone: '+91 98765 43210', email: 'priya@email.com', city: 'Delhi' },
  { id: 'C-1004', name: 'Sneha Desai', phone: '+91 87654 32109', email: 'sneha@email.com', city: 'Pune' },
  { id: 'C-1005', name: 'Arjun Mehta', phone: '+91 65432 10987', email: 'arjun@email.com', city: 'Bangalore' },
  { id: 'C-1006', name: 'Vikram Malhotra', phone: '+91 54321 09876', email: 'vikram@email.com', city: 'Hyderabad' },
  { id: 'C-1007', name: 'Ananya Singh', phone: '+91 43210 98765', email: 'ananya@email.com', city: 'Chennai' },
  { id: 'C-1008', name: 'Kavya Reddy', phone: '+91 54321 09876', email: 'kavya@email.com', city: 'Mumbai' },
  { id: 'C-1010', name: 'Rohan Nair', phone: '+91 43210 98765', email: 'rohan@email.com', city: 'Kochi' },
];

export const mockAvailableUnits = [
  { id: 'U-701', number: 'F-1101', project: 'Skyline Residences', projectId: 'P-1', builderId: 'B-01', builderName: 'Prestige Group', config: '3 BHK', floor: 11, tower: 'Tower F', price: '₹3.9 Cr', area: '1850 sqft' },
  { id: 'U-702', number: 'G-0402', project: 'Zenith Towers', projectId: 'P-2', builderId: 'B-02', builderName: 'DLF Limited', config: '2 BHK', floor: 4, tower: 'Tower G', price: '₹2.6 Cr', area: '1250 sqft' },
  { id: 'U-703', number: 'H-1801', project: 'Oasis Greens', projectId: 'P-3', builderId: 'B-03', builderName: 'Sobha Developers', config: '4 BHK', floor: 18, tower: 'Tower H', price: '₹5.5 Cr', area: '2400 sqft' },
  { id: 'U-704', number: 'A-0601', project: 'Skyline Residences', projectId: 'P-1', builderId: 'B-01', builderName: 'Prestige Group', config: '2 BHK', floor: 6, tower: 'Tower A', price: '₹3.1 Cr', area: '1350 sqft' },
  { id: 'U-705', number: 'B-1502', project: 'Zenith Towers', projectId: 'P-2', builderId: 'B-02', builderName: 'DLF Limited', config: '3 BHK', floor: 15, tower: 'Tower B', price: '₹4.0 Cr', area: '1750 sqft' },
];
